In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/aldinwhyudii/student-depression-and-lifestyle-100k-data/student_lifestyle_100k.csv

In [2]:
df = pd.read_csv('/kaggle/input/datasets/aldinwhyudii/student-depression-and-lifestyle-100k-data/student_lifestyle_100k.csv')
df.drop('Student_ID',axis=1)
df.head(3)

,Student_ID,Age,Gender,Department,CGPA,Sleep_Duration,Study_Hours,Social_Media_Hours,Physical_Activity,Stress_Level,Depression
0,1001,22,Female,Science,3.50,7.3,3.3,3.4,114,5,False
1,1002,20,Male,Engineering,2.72,5.5,7.2,6.0,142,2,False
2,1003,20,Male,Medical,3.01,5.4,2.3,1.8,137,3,False

In [3]:
df = pd.get_dummies(df,columns=['Gender','Department'],drop_first=True)

In [4]:
df.head(3)

,Student_ID,Age,CGPA,Sleep_Duration,Study_Hours,Social_Media_Hours,Physical_Activity,Stress_Level,Depression,Gender_Male,Department_Business,Department_Engineering,Department_Medical,Department_Science
0,1001,22,3.50,7.3,3.3,3.4,114,5,False,False,False,False,False,True
1,1002,20,2.72,5.5,7.2,6.0,142,2,False,True,False,True,False,False
2,1003,20,3.01,5.4,2.3,1.8,137,3,False,True,False,False,True,False

In [5]:
y = df['Depression']
x = df.drop('Depression',axis=1)

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [7]:
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.9,random_state=42)

In [8]:
rf = RandomForestClassifier()
model = rf.fit(x_train,y_train)

In [9]:
model.score(x_test,y_test)

0.8998

In [10]:
df['Depression'].value_counts()

Depression
False    89938
True     10062
Name: count, dtype: int64

In [11]:
sonuc = model.predict(x_test)
dfs = pd.DataFrame()
dfs['sonuc']=sonuc
dfs['gercek']=y_test.values
dfs['sonuc'].value_counts()

sonuc
False    9953
True       47
Name: count, dtype: int64

In [12]:
dfs['gercek'].value_counts()

gercek
False    9009
True      991
Name: count, dtype: int64

In [13]:
dfs['truebil'] = (dfs['gercek']==True) & (dfs['sonuc']==True)

In [14]:
dfs['truebil'].value_counts()

truebil
False    9982
True       18
Name: count, dtype: int64

In [15]:
18/51

0.35294117647058826

In [16]:
from sklearn.metrics import precision_score, recall_score, f1_score

In [17]:
precision = precision_score(dfs['gercek'],dfs['sonuc'])

In [18]:
18/991

0.018163471241170535

In [19]:
recall = recall_score(dfs['gercek'],dfs['sonuc'])

In [20]:
2*(precision*recall)/(precision+recall)

0.034682080924855495

In [21]:
f1 = f1_score(dfs['gercek'],dfs['sonuc'])