<a href="https://colab.research.google.com/github/eerenkurt/ml-studies/blob/main/12-feature-scaling-and-normalization/aircraft_price_prediction_scaling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler,MinMaxScaler

In [ ]:
df = pd.read_csv('plane.csv')

In [ ]:
df.head(3)

                     Model Name Engine Type  ... Range N.M.      Price
0  100 Darter (S.L. Industries)      Piston  ...        370  1300000.0
1                   7 CCM Champ      Piston  ...        190  1230000.0
2  100 Darter (S.L. Industries)      Piston  ...        210  1600000.0

[3 rows x 16 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517 entries, 0 to 516
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Model Name               517 non-null    object
 1   Engine Type              517 non-null    object
 2   HP or lbs thr ea engine  517 non-null    object
 3   Max speed Knots          497 non-null    object
 4   Rcmnd cruise Knots       507 non-null    float64
 5   Stall Knots dirty        502 non-null    float64
 6   Fuel gal/lbs             517 non-null    int64
 7   All eng rate of climb    513 non-null    object
 8   Eng out rate of climb    491 non-null    float64
 9   Takeoff over 50ft        492 non-null    float64
 10  Landing over 50ft        517 non-null    object
 11  Empty weight lbs         516 non-null    object
 12  Length ft/in             517 non-null    object
 13  Wing span ft/in          517 non-null    object
 14  Range N.M.               499 non-null    object
 15  Price                    507 non-null    float64
dtypes: float64(5), int64(1), object(10)
memory usage: 64.8+ KB

In [ ]:
df=df[["Rcmnd cruise Knots","Stall Knots dirty","Fuel gal/lbs","Eng out rate of climb","Price"]]

In [ ]:
df.head(3)
df=df.dropna()

In [ ]:
y = df["Price"]
x = df.drop("Price",axis=1)

In [ ]:
# Y için normalizasyon yapılmaz

# Outlier etkisini azaltır

# Model performansı artar

In [ ]:
ss = StandardScaler()
x2 = ss.fit_transform(x)

In [ ]:
x2 = pd.DataFrame(x2)
x2.head(3)

          0         1         2         3
0 -1.068341 -0.904960 -0.301214 -1.011179
1 -1.148585 -1.027513 -0.306625 -1.177365
2 -1.198738 -1.456449 -0.305594 -1.403563

In [ ]:
x2[2].mean()

np.float64(-6.178632484870436e-17)

In [ ]:
x2[2].std()

1.001088731950106

In [ ]:
mm = MinMaxScaler()

In [ ]:
x3 = mm.fit_transform(x)

In [ ]:
x3 = pd.DataFrame(x3)

In [ ]:
x3.head(3)

          0         1         2         3
0  0.051724  0.215909  0.000814  0.074541
1  0.032020  0.193182  0.000102  0.044254
2  0.019704  0.113636  0.000237  0.003029

In [ ]:
x3[0].max()

1.0

In [ ]:
x3[0].min()

0.0

In [ ]:
mm2 = MinMaxScaler(feature_range= (0,10))

In [ ]:
x4 = mm2.fit_transform(x)

In [ ]:
x4 = pd.DataFrame(x4)

In [ ]:
x4.head(3)

          0         1         2         3
0  0.517241  2.159091  0.008139  0.745415
1  0.320197  1.931818  0.001017  0.442537
2  0.197044  1.136364  0.002374  0.030288

In [ ]:
x4[0].max()

10.000000000000002

In [ ]:
x4[0].min()

0.0