<a href="https://colab.research.google.com/github/eerenkurt/ml-studies/blob/main/06-model-generalization-and-diamonds/diamond_price_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# UnderFitting
# OverFitting
# BalancedFiting

In [ ]:
import seaborn as sns
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [ ]:
df = sns.load_dataset("diamonds")

In [ ]:
df.head(3)

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31

In [ ]:
df = pd.get_dummies(df, columns = ["cut","color","clarity"],drop_first=True)

In [ ]:
df.head(3)

   carat  depth  table  ...  clarity_SI1  clarity_SI2  clarity_I1
0   0.23   61.5   55.0  ...        False         True       False
1   0.21   59.8   61.0  ...         True        False       False
2   0.23   56.9   65.0  ...        False        False       False

[3 rows x 24 columns]

In [ ]:
y = df["price"]
x = df.drop("price",axis=1)

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y,random_state=19,train_size=0.76)

In [ ]:
lm = LinearRegression()
model = lm.fit(x_train,y_train)

In [ ]:
model.score(x_test,y_test)

0.92006452446344

In [ ]:
model.score(x_train,y_train)

0.9196844286376016

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 24 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   carat          53940 non-null  float64
 1   depth          53940 non-null  float64
 2   table          53940 non-null  float64
 3   price          53940 non-null  int64
 4   x              53940 non-null  float64
 5   y              53940 non-null  float64
 6   z              53940 non-null  float64
 7   cut_Premium    53940 non-null  bool
 8   cut_Very Good  53940 non-null  bool
 9   cut_Good       53940 non-null  bool
 10  cut_Fair       53940 non-null  bool
 11  color_E        53940 non-null  bool
 12  color_F        53940 non-null  bool
 13  color_G        53940 non-null  bool
 14  color_H        53940 non-null  bool
 15  color_I        53940 non-null  bool
 16  color_J        53940 non-null  bool
 17  clarity_VVS1   53940 non-null  bool
 18  clarity_VVS2   53940 non-null  bool
 19  clarity_VS1    53940 non-null  bool
 20  clarity_VS2    53940 non-null  bool
 21  clarity_SI1    53940 non-null  bool
 22  clarity_SI2    53940 non-null  bool
 23  clarity_I1     53940 non-null  bool
dtypes: bool(17), float64(6), int64(1)
memory usage: 3.8 MB